# Use an official Codespaces image
FROM mcr.microsoft.com/vscode/devcontainers/universal:linux

# Install any additional tools you need here
# For example, to install HTTPie
RUN sudo apt-get update && sudo apt-get install -y httpie
